image: proboci/ubuntu-14.04-lamp:php-7.0
steps:
  - name: Test step
    command: 'for i in {1..20}; do echo $i; sleep 1s; done;'
  - name: Test step TWO
    command: 'for i in {1..20}; do echo $i; sleep 1s; done;'
  - name: Test step three
    command: 'for i in {1..20}; do echo $i; sleep 1s; done;'
  - name: Test step four
    command: 'for i in {1..20}; do echo $i; sleep 1s; done;'
