image: proboci/ubuntu-14.04-lamp:php-7.0
steps:
  - name: symlink maker.
    command: 'ln -s $SRC_DIR  /var/www/html'
  - name: ansi test 
    command: echo "\n\n\033[1;33;40m 33;40  \033[1;33;41m 33;41  \033[1;33;42m 33;42  \033[1;33;43m 33;43  \033[1;33;44m 33;44  \033[1;33;45m 33;45  \033[1;33;46m 33;46  \033[1m\033[0\n\n\033[1;33;42m >> Tests OK\n\n"
  - name: run lighthouse!
    plugin: Lighthouse
    categories:
      - seo: 64
      - performance: 87
  
