image: proboci/ubuntu-14.04-lamp:php-7.0
steps:
  - name: symlink maker.
    command: 'ln -s $SRC_DIR  /var/www/html'
  - name: run lighthouse!
    plugin: Lighthouse
    categories:
      - seo: 32
      - performance: 87
  
