image: proboci/ubuntu-14.04-lamp:php-7.0
steps:
  - name: Install lighthouse
    plugin: Script
    script: 
      - npm cache clean -f
      - npm install -g n
      - n stable
      - npm install -g lighthouse
  - name: Run Lighthouse audits
    plugin: Script
    script: 
      - lighthouse https://zivtech.com --chrome-flags="--no-sandbox=true --disable-setuid-sandbox --headless" --output-path=./lighthouse-results.html
  - name: Test step!
    plugin: Output
    output: '<h1>Test header</h1> <a href="https://google.com">Google</a>'
  - name: Display Lighthouse results
    plugin: Output
    output: "$(<./lighthouse-results.html)"
